# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "remill-template"

[variables]
GFLAGS_USE_TARGET_NAMESPACE = true

[find-package.remill]

[target.remill-example]
type = "executable"
sources = ["src/example.cpp"]
link-libraries = ["::remill"]
